# Read the Docs configuration file

version: "2"  # Version of the configuration file format

# Build environment configuration
build:
  os: "ubuntu-22.04"  # Operating system to use for the build
  tools:
    python: "3.10"  # Python version to use for the build

# Python dependencies installation
python:
  install:
    - requirements: docs/requirements.txt  # Path to your requirements.txt file

# Sphinx configuration
sphinx:
  configuration: docs/source/conf.py  # Path to your Sphinx conf.py file

# Additional options (optional)
formats:
  - html  # Specifies the output format for the build
  - pdf  # Optional: Generates PDF output if needed

